### PR TITLE
Failing with HTTP status code if >= 400

### PR DESCRIPTION
**Pull request by sommestad**
Makes it easier to handle error scenarios where API client is used.

---

:warning: 

This is likely to be a breaking change, since many API's rely on this always calling back with 500.

### CODE REVIEW

**Comment by sommestad** [comment]
Ping @dbrockman for 2nd opinion.

**Comment by dbrockman** [comment]
I think it's a good change. Maybe we want to pick a different default code when the respons is not expected but still 2xx?

**Comment by sommestad** [comment]
Yeah, I just wrote that down :) 

I'll pick a 4xx or 5xx and use that for that particular case.

**Comment by petrenkotino** [comment]
This is something we had as a discussion from the beginning, I think it's a good change as well.

**Comment by sommestad** [comment]
417 maybe

**Comment by dbrockman** [comment]
:+1:

**Comment by petrenkotino** [comment]
Squash and I'll merge

**Comment by sommestad** [comment]
I was actually thinking NOT to squash, since they're slightly different (we might want to revert parts of it or something).

**Comment by petrenkotino** [comment]
OK. That might be something that we would like to do in the near future. Are you done with the PR, or you still have something to add?

**Comment by sommestad** [comment]
I'm thinking it's done.

**Pull request merged**
